name: Simply Grey
markdown: redcarpet
pygments: true
github: https://www.github.com/chucongqing
about: NOPE
urls:
    - text: github
      url: https://github.com/chucongqing
    - text: email
      url: mailto:chucongqing@gmail.com


title : The Place

author : ccq
name : ccq
email : chucongqing@gmail.com
github: github.com/chucongqing
twitter: private

